//import _ from 'lodash';
import React, { Component } from 'react';
import { connect } from 'react-redux';
import * as actions from '../../actions';
import './Landing.css';
import background from '../../images/Cuts.png';
//import { Card, Segment, Grid, Header, Icon } from 'semantic-ui-react';

class Landing extends Component {
  render() {
    return (
      <div className="container">
        <div className="header">
          <header>
          </header>
        </div>
        <div className="content">
          <p>Connect with safe and reliable experts for all of your crypto needs.</p>
        </div>

        <div className="filler">
          <p>
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
            This is filler. This is filler. This is filler. This is filler.
          </p>
        </div>
        <div className="footer">
          <h1>Footer</h1>
        </div>
      </div>
    );
  }
}

function mapStateToProps({ application }) {
  return { application };
}

export default connect(mapStateToProps, actions)(Landing);
